apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.app.namespace }}-selfsigned
  namespace: {{ .Values.app.namespace }}
spec:
  secretName: {{ .Values.app.tlsSecret }}
  commonName: {{ .Values.app.fqdn }}
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-issuer
  dnsNames:
    - {{ .Values.app.fqdn }}