apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: {{ .Values.service.name }}
    app.kubernetes.io/part-of: {{ .Values.app.namespace }}
  name: {{ .Values.service.name }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.service.containerPort }}
  - name: https
    port: 443
    protocol: TCP
    targetPort: {{ .Values.service.containerPort }}
  selector:
    app.kubernetes.io/name: {{ .Values.service.name }}